### ISSUE TITLE
$row.sentence$ Occurences is blank

### ISSUE THREAD

**Issue by dalward** [geekusa/nlp-text-analytics#1]
Running Splunk 7.2.0
When using Counts and clicking on "Top Parts-of-Speech" or "Top Terms", new sub-panel with title "$row.sentence$ Occurences" 

![row sentence](https://user-images.githubusercontent.com/8324588/53521901-21e60300-3a8e-11e9-8e05-51c9296e68bb.png)

**Comment by dalward** [comment]
i tried changing row.sentence to click.value and this seems to fix it...but could have other consequences.

**Comment by geekusa** [comment]
Ah nice catch... is a remnant of the original test build. Looks like it is just being used to set another token so I think your fix should work but I will confirm. Thanks!

**Comment by geekusa** [comment]
updated in commit 41666b692afc47a442a74a6522e011476696bd56, elected to use and alias hidden column so that selection can still be made row-wise
