### ISSUE TITLE
Splunk Cloud compatibility

### ISSUE THREAD

**Issue by lindonm** [geekusa/nlp-text-analytics#3]
Not currently compatible/vetted with Splunk Cloud, though I did manage to get an older version installed on a different instance one, and would really love to be able to use it.

**Comment by geekusa** [comment]
I opened a support case (2862628) with Splunk, to ask that it be vetted.

**Comment by lindonm** [comment]
Great! Thanks, NLP has been really useful for us (IT ops team @ Department
of Education, Victoria Australia)

**Comment by geekusa** [comment]
I have released a new version 1.1.3 that passes appinspect API with the cloud tag on. I'm not sure how long it takes for it to show up on Splunk Cloud as I only have access to on prem. You used to have to ask for vetting but now that seems more automatic. So I'll continue to check for several days.

**Comment by geekusa** [comment]
@lindonm version 1.1.3 now shows compatible for Splunk Cloud.
